version: '2'

services:
    mq:
        image: rabbitmq
    gw:
        build:
            context: .
            dockerfile: gw/Dockerfile
        ports:
            - 8080:8000
        links:
            - mq
    cl:
        build:
            context: . 
            dockerfile: client/Dockerfile
        links:
            - mq
            - gw
    sr_db:
        image: postgres
        volumes: 
            - '~/course/Bigly/saver/db:/var/lib/postgresql/data'
    sr:
        build:
            context: .
            dockerfile: saver/Dockerfile
        links:
            - sr_db
        ports:
            - 80:8000
    sr_ext:
        build:
            context: .
            dockerfile: extractor/Dockerfile
        links:
            - sr
            - mq
