version: '2'

services:
    mq:
        image: rabbitmq
    gw:
        build:
            context: .
            dockerfile: gw/Dockerfile
        ports:
            - 80:8000
        links:
            - mq
    cl:
        build:
            context: client
            dockerfile: Dockerfile
        links:
            - mq
            - gw
    sr:
        build:
            context: saver
            dockerfile: Dockerfile
        links:
            - mq
        ports:
            - 8080:8000
